version: '3.1'
services:
  spring-docker:
    build: .
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - db
      - discovery-server
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always