server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://165.232.114.125:8761/eureka/
  instance:
    hostname: 165.232.114.125
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://165.232.114.125:8081/
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: http://165.232.114.125:8082/
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: http://165.232.114.125:8083/
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: http://165.232.114.125:8084/
          predicates:
            - Path=/api/inventory/**
