server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081/
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: http://product-service:8082/
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: http://order-service:8083/
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: http://invertory-service:8084/
          predicates:
            - Path=/api/inventory/**