server:
  port: 8080
spring:
  application:
    name: ap-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://165.232.114.125:8081/
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: http://product-service:8082/
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: http://order-service:8083/
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: http://invertory-service:8084/
          predicates:
            - Path=/api/inventory/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://165.232.114.125:8671/eureka/