spring:
  application:
    name: product-service
  data:
    mongodb:
      database: product_service
      port: 27017
      host: 165.232.114.125
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://165.232.114.125:8671/eureka/
server:
  port: 8082